#!/bin/bash
javac -cp commons-cli-1.4.jar: address4forensics.java

echo "Compiling.."
echo ""

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -L -b 128 --physical-known=12345678
java -cp commons-cli-1.4.jar: address4forensics -L -b 128 --physical-known=12345678

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -P --partition-start=128 -c 58 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -P --partition-start=128 -c 58 -k 4 -r 6 -t 2 -f 16

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -P -l 2 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -P -l 2 -k 4 -r 6 -t 2 -f 16

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -P -B -s 300 -l 2 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -P -B -s 300 -l 2 -k 4 -r 6 -t 2 -f 16

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -P -p 2 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -P -p 2 -k 4 -r 6 -t 2 -f 16

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -C -c 2 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -C -c 2 -k 4 -r 6 -t 2 -f 16

echo ""
echo "-----------------------------------------------------------------------------------------------------"
echo java -cp commons-cli-1.4.jar: address4forensics -L -l 2 -k 4 -r 6 -t 2 -f 16
java -cp commons-cli-1.4.jar: address4forensics -L -l 2 -k 4 -r 6 -t 2 -f 16
